#!/usr/bin/python

import sys
sys.path.insert(0, '/etc/fred/')
#import psyco
#psyco.full()

from fred_webadmin import adif
from option_parse import options

if __name__ == '__main__':
    if options.nperms or options.nperms_distinct:
        from fred_webadmin.info import print_nperms
        print_nperms(options.nperms_distinct)
    elif options.nperms_for_class:
        from fred_webadmin.info import print_nperms_for_class
        print_nperms_for_class(options.nperms_for_class)
    else:
        adif.runserver()
